In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

Data Generation
===

In [8]:
num_samples, num_features = 100, 5

In [9]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [10]:
print(data)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
 [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
 [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935]
 [0.30070006 0.11398436 0.82868133 0.04689632 0.62628715]
 [0.54758616 0.819287   0.19894754 0.8568503  0.35165264]
 [0.75464769 0.29596171 0.88393648 0.32551164 0.1650159 ]
 [0.39252924 0.09346037 0.82110566 0.15115202 0.38411445]
 [0.94426071 0.98762547 0.45630455 0.82612284 0.25137413]
 [0.59737165 0.90283176 0.53455795 0.59020136 0.03928177]
 [0.35718176 0.07961309 0.30545992 0.33071931 0.7738303 ]
 [0.03995921 0.42949218 0.31492687 0.63649114 0.34634715]
 [0.04309736 0.87991517 0.76324059 0.87809664 0.41750914]
 [0.60557756 0.51346663 0.59783665 0.26221566 0.30087131]
 [0.02539978 0

In [11]:
def standardize(x):
    ''' fill your code in here...
    '''
    x = x - np.mean(x,axis = 0) # subtract the mean on every column
    x = x / np.std(x,axis = 0) # normalize the matrix
    return x

std_data = standardize(data)

In [12]:

print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 1.09287762e+00 -1.54190401e+00  5.66788688e-01  7.84091861e-01
  -1.89538505e-02]
 [-9.82738852e-01 -9.46467225e-01  9.81380637e-01 -1.33446615e+00
  -1.44880725e+00]
 [ 7.66411252e-01  1.59004641e+00 -1.49077311e+00 -8.06337805e-02
   1.07605546e+00]
 [ 4.89799548e-01  8.12170988e-01 -5.49961174e-01  1.40161394e+00
   7.34267444e-01]
 [ 2.24019514e-01 -1.13416373e+00 -2.83773075e-01  5.11200381e-01
  -2.16520307e-01]
 [-1.88162630e-01  4.62962468e-01  1.73019006e-01  4.24452729e-01
   3.38475134e-01]
 [ 1.22163445e+00  1.40177600e-01  1.46536079e+00 -7.85815345e-01
  -1.44141850e+00]
 [-6.94469039e-01 -1.22881551e+00  1.20406462e+00 -1.78111381e+00
   4.26490991e-01]
 [ 2.43167471e-01  1.13969707e+00 -8.53607671e-01  1.17896051e+00
  -5.30891972e-01]
 [ 1.02955624e+00 -6.17708153e-01  1.38461234e+00 -7.62880596e-01
  -1.18151245e+00]
 [-3.45715509e-01 -1.29773816e+00  1.17931092e+00 -1.40009881e+00
  -4.17729270e-01]
 [ 1.74967816e+00  1.70500306e+00 -1.26866413e-02  1.06666331e+00